name: Docker push pr

on: 
  workflow_dispatch:
    inputs:
      dockerImageVersion:
        description: 'Docker image version'
        required: true

env:
  DOTNET_VERSION: 5.0.101
  CONFIGURATION: Release
  WEBAPP_PROJECT: src/DockerWorkflow.WebApp/DockerWorkflow.WebApp.csproj
  PUBLISH_FOLDER: src/DockerWorkflow.WebApp/bin/publish
  DOCKER_FILE: src/DockerWorkflow.WebApp/Dockerfile  
  GITHUB_DOCKER: https://docker.pkg.github.com
  GITHUB_IMAGE_NAME: docker.pkg.github.com/arnab-developer/dockerworkflow/dockerworkflow:${{ github.event.inputs.dockerImageVersion }}
  GITHUB_DOCKER_USER: Arnab-Developer

jobs:
  build-test:    
    name: Build and test
    runs-on: ubuntu-latest    
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}    
    - name: Restore dependencies
      run: dotnet restore
    - name: Build
      run: dotnet build --configuration ${{ env.CONFIGURATION }} --no-restore    
    - name: Test
      run: dotnet test --configuration ${{ env.CONFIGURATION }}

  github-package-deploy:
    name: GitHub package deploy
    runs-on: ubuntu-latest
    needs: build-test
    steps:
    - name: Checkout code
      uses: actions/checkout@v2      
    - name: Setup .NET
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: ${{ env.DOTNET_VERSION }}    
    - name: Restore dependencies
      run: dotnet restore
    - name: Publish
      run: dotnet publish ${{ env.WEBAPP_PROJECT }} --configuration ${{env.CONFIGURATION}} -o ${{ env.PUBLISH_FOLDER }}
    - name: Create docker image
      run: docker build -f ${{ env.DOCKER_FILE }} -t ${{ env.GITHUB_IMAGE_NAME }} .
    - name: Push docker image
      run: |
        docker login ${{ env.GITHUB_DOCKER }} -u ${{ env.GITHUB_DOCKER_USER }} -p '${{ secrets.GITHUB_TOKEN }}'
        docker push ${{ env.GITHUB_IMAGE_NAME }}